[project]
name = "pretinhafinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvlib>=0.2.7",
    "opencv-python>=4.12.0.88",
    "python-dotenv>=1.1.1",
    "tensorflow>=2.20.0",
    "ultralytics>=8.3.214",
]
